<!-- imu model-->
<robot name="my_imu" xmlns:xacro = "http://wiki.ros.org/xacro">

<xacro:property name = "imu_length"  value = "0.02" />
<xacro:property name = "imu_width"   value = "0.02" />
<xacro:property name = "imu_height"  value = "0.01" />

<xacro:property name = "imu_m"       value = "0.1"  /> <!-- weight -->

<xacro:property name = "imu_x"       value =  "-0.04"/>
<xacro:property name = "imu_y"       value =  "0"/>
<xacro:property name = "imu_z"       value =  "${base_link_length / 2 + imu_height / 2}"/>

<link name="imu">
    <visual>
        <geometry>
            <box size="${imu_length} ${imu_width} ${imu_height}"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <material name="green"><color rgba="0.0 1.0 0.0 0.0"/> <!-- green -->
        </material>
    </visual>
    <collision>
        <geometry>
            <box size="${imu_length} ${imu_width} ${imu_height}"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </collision>
    <xacro:Box_inertial_matrix m="${imu_m}" l="${imu_length}" w="${imu_width}" h="${imu_height}" />
</link>

<joint name="imu2base_link" type="fixed">
    <parent link="base_link"/>
    <child  link="imu"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0.0 0.0 0.0"/>
</joint>

<gazebo reference = "imu" >
    <material>Gazebo/Green</material> <!-- green -->
</gazebo>

</robot>